# Generated by Django 6.0.6 on 2026-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
