# Generated by Django 6.0.6 on 2026-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_page_section_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='text_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='text_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='text_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='key',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('events', 'Events')], max_length=40, unique=True),
        ),
    ]
