# Generated by Django 6.0.6 on 2026-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_gallery_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='ceo2_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='manager_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
