# Generated by Django 6.0.6 on 2026-07-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leadership_portraits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(blank=True, default='General', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, default='Available', max_length=120)),
                ('quantity', models.CharField(blank=True, max_length=120)),
                ('price', models.CharField(blank=True, max_length=120)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_colors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='key',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('events', 'Events'), ('services', 'Services')], max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.serviceitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
