# Generated by Django 6.0.6 on 2026-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(upload_to='home/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured video',
                'verbose_name_plural': 'Featured videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
