/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAccountRouteImport } from './routes/admin.account'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/admin/site',
  path: '/admin/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site': typeof AdminSiteRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site': typeof AdminSiteRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site': typeof AdminSiteRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/sitemap.xml'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/reviews'
    | '/admin/site'
    | '/employees/$id'
    | '/events/$id'
    | '/admin/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/reviews'
    | '/admin/site'
    | '/employees/$id'
    | '/events/$id'
    | '/admin'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/sitemap.xml'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/reviews'
    | '/admin/site'
    | '/employees/$id'
    | '/events/$id'
    | '/admin/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  EmployeesIdRoute: typeof EmployeesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/admin/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSiteRoute: AdminSiteRoute,
  EmployeesIdRoute: EmployeesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
